version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prod.db
      - NEXTAUTH_SECRET=your-secret-key
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      - ./prisma:/app/prisma
      - app_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加数据库服务（如果使用PostgreSQL）
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: southpole
  #     POSTGRES_USER: southpole_user
  #     POSTGRES_PASSWORD: southpole_pass
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # Redis用于缓存（可选）
  # redis:
  #   image: redis:7-alpine
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis_data:/data
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

volumes:
  app_data:
  # postgres_data:
  # redis_data: